from tkinter import *
root=Tk()
ab=Label(root,text='Student Entry Form:')
bc=Label(root,text='Student Name:')
cd=Label(root,text='Class:')
de=Label(root,text='Admin No:')
ef=Label(root,text='gender:')
fg=Label(root,text='last studied school')
gh=Label(root,text='city/town')
hi=Label(root,text='state')
cb=Entry(root)
dc=Entry(root)
ed=Entry(root)
fe=Entry(root)
gf=Entry(root)
hg=Entry(root)
ih=Entry(root)
ab.grid(row=0,sticky=E)
bc.grid(row=1,sticky=E)
cd.grid(row=2,sticky=E)
de.grid(row=3,sticky=E)
ef.grid(row=4,sticky=E)
fg.grid(row=5,sticky=E)
gh.grid(row=6,sticky=E)
hi.grid(row=7,sticky=E)
cb.grid(row=1,column=1)
dc.grid(row=2,column=1)
ed.grid(row=3,column=1)
fe.grid(row=4,column=1)
gf.grid(row=5,column=1)
hg.grid(row=6,column=1)
ih.grid(row=7,column=1)
root.mainloop()
c=Checkbutton(root,text="SUBMIT")
c.grid(columnspan=2)
lb=BitmapImage