from tkinter import *
root=Tk()
l1=Label(root,text="Welcome:")
l2=Label(root,text="Your Name:")
l3=Label(root,text="NO.of marks:")
l4=Label(root,text="City:")
l5=Label(root,text="Salary:")
l6=Label(root,text="Subject:")
l7=Label(root,text="class teacher of:")
b=Entry(root)
c=Entry(root)
d=Entry(root)
e=Entry(root)
f=Entry(root)
g=Entry(root)
l1.grid(row=0,sticky=E)
l2.grid(row=1,sticky=E)
l3.grid(row=2,sticky=E)
l4.grid(row=3,sticky=E)
l5.grid(row=4,sticky=E)
l6.grid(row=5,sticky=E)
l7.grid(row=6,sticky=E)
b.grid(row=1,column=1)
c.grid(row=2,column=1)
d.grid(row=3,column=1)
e.grid(row=4,column=1)
f.grid(row=5,column=1)
g.grid(row=6,column=1)
c=Checkbutton(root,text="SUBMIT")
c.grid(columnspan=2)
lb=BitmapImage
root.mainloop()
